[[OCCT]]
arch = "aarch64"
git-tree-sha1 = "9f320ebebf94e1ccfafe04b1db120a0b60657581"
os = "macos"

    [[OCCT.download]]
    sha256 = "649395efdac5cc310d41b6f8f8e2c03f61d6471789fae7e8b81880a34a1af35d"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.aarch64-apple-darwin.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a022a52ead042355737387b6c99caf022603deba"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "6d33821b525adf3d1dc82ec3fca7d926dada788dbefc8e52b76564f4ed64efe7"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.aarch64-linux-gnu-cxx03.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f32b26cbaaf8c3be780ee23e965cf5035558a7da"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "573a0625fd25c836261d3628974fdc1829eb2c82ff0f8c1576b8076140aedf84"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "587fe531f73eddf438a448cc024474de2f4e3a75"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "deec0f57b95f123974e530fe16fb5ef2dfece52e52af0ea74b092c91aa86956e"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.aarch64-linux-musl-cxx03.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3887e1ebd49db2ffd5b4ad3c60674a2c220a195e"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "d0ce6df4cb109ac5673e027d7aaf452710d54f0bf46973b589809ef10b35908e"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8026bac2437b044179dc033e544b33170f0cce9"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "877fba79cf4e16be53128e451c97ab5eda8fe57b4155d865d9754feda0f53529"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4ea820df8f7b053c1dbd7ca952a7903b44a58c6"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "ed0186507ef89620ba196aeb0606f5a79e962b3b16e3dcc29ff1235279d845cc"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90e94d3d95fef612e21774e48f65f52fc26ebe8c"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "18e15fcd75e35a18458d3de5e4e6483a458b68eea693cec9a4976831811c487c"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99408c2c129c480a40e7f7080d4be68a484e5235"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "4425dcb7d0f4b545252b59cfa78979eae8af9c681ac79fdfb3e83089ddf0eabd"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc84e60bae0c774f2c007980627cd7fe800dca8a"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "b0ec3be281f892dc86fdc899568083306e0371964cde021e418fde6912cd3627"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.i686-linux-gnu-cxx03.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98f130b459820eadaa728290b955b5f712373875"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "d9df7f0f18d4387026c9d51fe12fb89afe27316fc58b55ebc23348a00e4bf726"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.i686-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "028b2847b6a4fd32ef47ba47e225eab0c2bf4203"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "c8ae1f4ddbaae1ce8b4e70361986f00de206d3019c0c180433990bbae77af8b8"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.i686-linux-musl-cxx03.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03353c634a609d6d11ddfd59967fec9be7559e0d"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "45773b4aa3bbd4b1f488948e890238598fda9f344bd36518f75ffaf801869a62"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.i686-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e3e93ae3ffa1be13682cdf336c5e470eb2f84e0e"
os = "windows"

    [[OCCT.download]]
    sha256 = "950d898c3af8781889308fb59ebc590aaac03df7ae6a3d77c554b7afd276e840"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.i686-w64-mingw32-cxx11.tar.gz"
[[OCCT]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7e2b5eb63a0c94873eeb1c630d9bed64e9d64af"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "e504f4f96ef6aedfe2682a0c15a0a39f1add66093feb6a3cb2c95a24305c501e"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[OCCT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e7d3ac087c9490f934f873e125e37075b036ffb"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "512c8f4ab7005b48875487b27e9cde32f9f79433876d3d04562ba094a7f9f3d1"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
git-tree-sha1 = "b217ceba0a5ec2a88391b568da752e62996a8116"
os = "macos"

    [[OCCT.download]]
    sha256 = "dbcedd7e5897839b01197417662f1a3f6e9c1506e349e1e32f3f3965b1e52226"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-apple-darwin.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "681cfcc689d8a2b0afe18209d30c0a4f2c85d156"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "aedc4351efcf8e1e32d36045ce4ceee3f32c7b930cb37ff3b8462748ac10d89a"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-linux-gnu-cxx03.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4e17c8e7b32081ca18e7e3074632da780be8fb6"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "04c411943af2162b7de051cdac9696a8a0bb3eac7cb4ab03fb96d749baad8a3e"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88358aba2ef5a3f19bf849f1e4cc6aceda0060d1"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "458b6c1714412f0fad8e9eb110b42b2e752d88a4d63b2bee8cbdb81f492b51f4"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-linux-musl-cxx03.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fbbaacabe38fcc72eeb37bf2130ade89417cd29"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "ce1a2073740349dda25058124a0cb23c27c4b0343ffcdcdf4481736ccf90bed1"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
git-tree-sha1 = "56f4d5e81f611d9258603e9f56e56493b895d90e"
os = "freebsd"

    [[OCCT.download]]
    sha256 = "240d930106ffdb08d7f186753fc9f073316e23eb0fa5ac0ec7b1856ba6e0a308"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-unknown-freebsd.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bbb5dd6f18a99656755e7b52bab7d596c28475e3"
os = "windows"

    [[OCCT.download]]
    sha256 = "f77b4cf07acdd2ff9c0754581862bbd143f2d1eba9f2a6a7a5382dce30902b6c"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.6.2+1/OCCT.v7.6.2.x86_64-w64-mingw32-cxx11.tar.gz"
