[[OCCT]]
arch = "aarch64"
git-tree-sha1 = "e694101d9d2790399af6bb4bc695ed0a7304cdc0"
os = "macos"

    [[OCCT.download]]
    sha256 = "cf528bc810b328478e3196d01cc9fd4e8933778d78ead61327ab9832e14d328e"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.aarch64-apple-darwin.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93abf098510b3b5f145d3a520ca6aa27e5b8ad03"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "0326c8ddd021bc2672266787b6fa75e40c0afb249179aec0ee46dd442b29424a"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.aarch64-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eed7faf0856f956fdcf365341a0b0216b2eecd6"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "b66f295abb97c85817e249715f4fa8704fb98db01b5037bf1e9c155310b46c8d"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.aarch64-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "aarch64"
git-tree-sha1 = "b38dc855a714bfcb4c9eedf392df979eb1916ca9"
os = "freebsd"

    [[OCCT.download]]
    sha256 = "daefbad11028df932289fa80db826fb9d5c4f725fc561f5375b6bc940276b31c"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.aarch64-unknown-freebsd.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "058c11a536ceb5b34fca10c272a6ab5f771f5c82"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "ba3b8a416a72389bce46efafc4224425eef5c783838f0e2757f161756f28e575"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[OCCT]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee46a3eb6281de39c117f8873d059e4f88c5226b"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "1c65582e21d26549cba7b99ba42559c71e292b430b9fd9d94241d1d121634127"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a639787c6bf7a3748a3409682d63e0947be0bbd"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "e7264d4e1ab77f346cf0f836ee16cf41dd46c844ce824d67165e5af1dc370550"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.i686-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60840c71846c5e3c7a345736ec7462ecf20fed4d"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "8f34d40313794cfa561893c07406fc25a848b8e6e803fc72b06ebd3cae287da2"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.i686-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8efe39322d9d3a637dba2684351dbce17313c5f5"
os = "windows"

    [[OCCT.download]]
    sha256 = "8542f52da4cd08df893d12f1bd721605b944372c36951bf145895567a2127417"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.i686-w64-mingw32-cxx11.tar.gz"
[[OCCT]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b89b87ce4cbd44ca73f8b4f0c01e8fae2ca8c60a"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "480a337cb7aa994379b3353d3e360def91b6c3c53b71fbe86dba442dde698990"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dee1e6528cd1e3131b041db5ce64e54172c2e22"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "0f2e2dd34052d1a1e31630a0122d112e6132f0a33ec5b1a967ef4acbbfd3a450"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.riscv64-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
git-tree-sha1 = "81d081a5ee977bd0ff9da469b7d73277ca7319f2"
os = "macos"

    [[OCCT.download]]
    sha256 = "f10cdf86ba487804daf67d51efdf309224195459921e9452e97188c1a13218a0"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.x86_64-apple-darwin.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a40c20966be12089380db29c31adc6be9bb2436"
libc = "glibc"
os = "linux"

    [[OCCT.download]]
    sha256 = "a86b11a4eb68b6f8e3b1f1e5cb8114de096416ecccf19c6ad2e453a76ff88062"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.x86_64-linux-gnu-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "084981e6040c79ba7b7f777635bcc1ee86dab4f9"
libc = "musl"
os = "linux"

    [[OCCT.download]]
    sha256 = "ffeb34df3d7cbfd1473ba9c5f9a2a0f5fe7c92d72f306e5f3f4bb4d26084919a"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.x86_64-linux-musl-cxx11.tar.gz"
[[OCCT]]
arch = "x86_64"
git-tree-sha1 = "af11e51687a6c8baac7301ab7080ffc378bfb752"
os = "freebsd"

    [[OCCT.download]]
    sha256 = "0e0a96b8d06d3d1698d44c0b5d5575a8fc0a16ca088704db50f5a8ffda126c25"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.x86_64-unknown-freebsd.tar.gz"
[[OCCT]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a75a3873e6ed193af9ad9a8a7cd86774e3c96293"
os = "windows"

    [[OCCT.download]]
    sha256 = "2bf8abb2f6bdf82207c147086d4feaa0fa1cbbed85bbf9ba00551659d36eb368"
    url = "https://github.com/JuliaBinaryWrappers/OCCT_jll.jl/releases/download/OCCT-v7.9.2+0/OCCT.v7.9.2.x86_64-w64-mingw32-cxx11.tar.gz"
