# Autogenerated wrapper script for OCCT_jll for i686-linux-musl-cxx11
export libTKBO, libTKBRep, libTKBin, libTKBinL, libTKBinXCAF, libTKBool, libTKCAF, libTKCDF, libTKFeat, libTKFillet, libTKG2d, libTKG3d, libTKGeomAlgo, libTKGeomBase, libTKHLR, libTKIGES, libTKLCAF, libTKMath, libTKMesh, libTKOffset, libTKPrim, libTKRWMesh, libTKSTEP, libTKSTEP209, libTKSTEPAttr, libTKSTEPBase, libTKSTL, libTKService, libTKShHealing, libTKTopAlgo, libTKV3d, libTKVCAF, libTKVRML, libTKXCAF, libTKXDEIGES, libTKXDESTEP, libTKXMesh, libTKXSBase, libTKXml, libTKXmlL, libTKXmlXCAF, libTKernel

using FreeType2_jll
using Libglvnd_jll
using Xorg_libX11_jll
using Xorg_libXext_jll
using Xorg_libXfixes_jll
using Xorg_libXft_jll
using Xorg_libXinerama_jll
using Xorg_libXrender_jll
JLLWrappers.@generate_wrapper_header("OCCT")
JLLWrappers.@declare_library_product(libTKBO, "libTKBO.so.7.7")
JLLWrappers.@declare_library_product(libTKBRep, "libTKBRep.so.7.7")
JLLWrappers.@declare_library_product(libTKBin, "libTKBin.so.7.7")
JLLWrappers.@declare_library_product(libTKBinL, "libTKBinL.so.7.7")
JLLWrappers.@declare_library_product(libTKBinXCAF, "libTKBinXCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKBool, "libTKBool.so.7.7")
JLLWrappers.@declare_library_product(libTKCAF, "libTKCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKCDF, "libTKCDF.so.7.7")
JLLWrappers.@declare_library_product(libTKFeat, "libTKFeat.so.7.7")
JLLWrappers.@declare_library_product(libTKFillet, "libTKFillet.so.7.7")
JLLWrappers.@declare_library_product(libTKG2d, "libTKG2d.so.7.7")
JLLWrappers.@declare_library_product(libTKG3d, "libTKG3d.so.7.7")
JLLWrappers.@declare_library_product(libTKGeomAlgo, "libTKGeomAlgo.so.7.7")
JLLWrappers.@declare_library_product(libTKGeomBase, "libTKGeomBase.so.7.7")
JLLWrappers.@declare_library_product(libTKHLR, "libTKHLR.so.7.7")
JLLWrappers.@declare_library_product(libTKIGES, "libTKIGES.so.7.7")
JLLWrappers.@declare_library_product(libTKLCAF, "libTKLCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKMath, "libTKMath.so.7.7")
JLLWrappers.@declare_library_product(libTKMesh, "libTKMesh.so.7.7")
JLLWrappers.@declare_library_product(libTKOffset, "libTKOffset.so.7.7")
JLLWrappers.@declare_library_product(libTKPrim, "libTKPrim.so.7.7")
JLLWrappers.@declare_library_product(libTKRWMesh, "libTKRWMesh.so.7.7")
JLLWrappers.@declare_library_product(libTKSTEP, "libTKSTEP.so.7.7")
JLLWrappers.@declare_library_product(libTKSTEP209, "libTKSTEP209.so.7.7")
JLLWrappers.@declare_library_product(libTKSTEPAttr, "libTKSTEPAttr.so.7.7")
JLLWrappers.@declare_library_product(libTKSTEPBase, "libTKSTEPBase.so.7.7")
JLLWrappers.@declare_library_product(libTKSTL, "libTKSTL.so.7.7")
JLLWrappers.@declare_library_product(libTKService, "libTKService.so.7.7")
JLLWrappers.@declare_library_product(libTKShHealing, "libTKShHealing.so.7.7")
JLLWrappers.@declare_library_product(libTKTopAlgo, "libTKTopAlgo.so.7.7")
JLLWrappers.@declare_library_product(libTKV3d, "libTKV3d.so.7.7")
JLLWrappers.@declare_library_product(libTKVCAF, "libTKVCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKVRML, "libTKVRML.so.7.7")
JLLWrappers.@declare_library_product(libTKXCAF, "libTKXCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKXDEIGES, "libTKXDEIGES.so.7.7")
JLLWrappers.@declare_library_product(libTKXDESTEP, "libTKXDESTEP.so.7.7")
JLLWrappers.@declare_library_product(libTKXMesh, "libTKXMesh.so.7.7")
JLLWrappers.@declare_library_product(libTKXSBase, "libTKXSBase.so.7.7")
JLLWrappers.@declare_library_product(libTKXml, "libTKXml.so.7.7")
JLLWrappers.@declare_library_product(libTKXmlL, "libTKXmlL.so.7.7")
JLLWrappers.@declare_library_product(libTKXmlXCAF, "libTKXmlXCAF.so.7.7")
JLLWrappers.@declare_library_product(libTKernel, "libTKernel.so.7.7")
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll, Libglvnd_jll, Xorg_libX11_jll, Xorg_libXext_jll, Xorg_libXfixes_jll, Xorg_libXft_jll, Xorg_libXinerama_jll, Xorg_libXrender_jll)
    JLLWrappers.@init_library_product(
        libTKBO,
        "lib/libTKBO.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBRep,
        "lib/libTKBRep.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBin,
        "lib/libTKBin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinL,
        "lib/libTKBinL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinXCAF,
        "lib/libTKBinXCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBool,
        "lib/libTKBool.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCAF,
        "lib/libTKCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCDF,
        "lib/libTKCDF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFeat,
        "lib/libTKFeat.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFillet,
        "lib/libTKFillet.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG2d,
        "lib/libTKG2d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG3d,
        "lib/libTKG3d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomAlgo,
        "lib/libTKGeomAlgo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomBase,
        "lib/libTKGeomBase.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKHLR,
        "lib/libTKHLR.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKIGES,
        "lib/libTKIGES.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKLCAF,
        "lib/libTKLCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMath,
        "lib/libTKMath.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMesh,
        "lib/libTKMesh.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKOffset,
        "lib/libTKOffset.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKPrim,
        "lib/libTKPrim.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKRWMesh,
        "lib/libTKRWMesh.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEP,
        "lib/libTKSTEP.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEP209,
        "lib/libTKSTEP209.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEPAttr,
        "lib/libTKSTEPAttr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEPBase,
        "lib/libTKSTEPBase.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTL,
        "lib/libTKSTL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKService,
        "lib/libTKService.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKShHealing,
        "lib/libTKShHealing.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKTopAlgo,
        "lib/libTKTopAlgo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKV3d,
        "lib/libTKV3d.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKVCAF,
        "lib/libTKVCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKVRML,
        "lib/libTKVRML.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXCAF,
        "lib/libTKXCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXDEIGES,
        "lib/libTKXDEIGES.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXDESTEP,
        "lib/libTKXDESTEP.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXMesh,
        "lib/libTKXMesh.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXSBase,
        "lib/libTKXSBase.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXml,
        "lib/libTKXml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlL,
        "lib/libTKXmlL.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlXCAF,
        "lib/libTKXmlXCAF.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKernel,
        "lib/libTKernel.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
