# Autogenerated wrapper script for OCCT_jll for x86_64-w64-mingw32-cxx03
export libTKBO, libTKBRep, libTKBin, libTKBinL, libTKBinXCAF, libTKBool, libTKCAF, libTKCDF, libTKFeat, libTKFillet, libTKG2d, libTKG3d, libTKGeomAlgo, libTKGeomBase, libTKHLR, libTKIGES, libTKLCAF, libTKMath, libTKMesh, libTKOffset, libTKPrim, libTKRWMesh, libTKSTEP, libTKSTEP209, libTKSTEPAttr, libTKSTEPBase, libTKSTL, libTKService, libTKShHealing, libTKTopAlgo, libTKV3d, libTKVCAF, libTKVRML, libTKXCAF, libTKXDEIGES, libTKXDESTEP, libTKXMesh, libTKXSBase, libTKXml, libTKXmlL, libTKXmlXCAF, libTKernel

using FreeType2_jll
JLLWrappers.@generate_wrapper_header("OCCT")
JLLWrappers.@declare_library_product(libTKBO, "libTKBO.dll")
JLLWrappers.@declare_library_product(libTKBRep, "libTKBRep.dll")
JLLWrappers.@declare_library_product(libTKBin, "libTKBin.dll")
JLLWrappers.@declare_library_product(libTKBinL, "libTKBinL.dll")
JLLWrappers.@declare_library_product(libTKBinXCAF, "libTKBinXCAF.dll")
JLLWrappers.@declare_library_product(libTKBool, "libTKBool.dll")
JLLWrappers.@declare_library_product(libTKCAF, "libTKCAF.dll")
JLLWrappers.@declare_library_product(libTKCDF, "libTKCDF.dll")
JLLWrappers.@declare_library_product(libTKFeat, "libTKFeat.dll")
JLLWrappers.@declare_library_product(libTKFillet, "libTKFillet.dll")
JLLWrappers.@declare_library_product(libTKG2d, "libTKG2d.dll")
JLLWrappers.@declare_library_product(libTKG3d, "libTKG3d.dll")
JLLWrappers.@declare_library_product(libTKGeomAlgo, "libTKGeomAlgo.dll")
JLLWrappers.@declare_library_product(libTKGeomBase, "libTKGeomBase.dll")
JLLWrappers.@declare_library_product(libTKHLR, "libTKHLR.dll")
JLLWrappers.@declare_library_product(libTKIGES, "libTKIGES.dll")
JLLWrappers.@declare_library_product(libTKLCAF, "libTKLCAF.dll")
JLLWrappers.@declare_library_product(libTKMath, "libTKMath.dll")
JLLWrappers.@declare_library_product(libTKMesh, "libTKMesh.dll")
JLLWrappers.@declare_library_product(libTKOffset, "libTKOffset.dll")
JLLWrappers.@declare_library_product(libTKPrim, "libTKPrim.dll")
JLLWrappers.@declare_library_product(libTKRWMesh, "libTKRWMesh.dll")
JLLWrappers.@declare_library_product(libTKSTEP, "libTKSTEP.dll")
JLLWrappers.@declare_library_product(libTKSTEP209, "libTKSTEP209.dll")
JLLWrappers.@declare_library_product(libTKSTEPAttr, "libTKSTEPAttr.dll")
JLLWrappers.@declare_library_product(libTKSTEPBase, "libTKSTEPBase.dll")
JLLWrappers.@declare_library_product(libTKSTL, "libTKSTL.dll")
JLLWrappers.@declare_library_product(libTKService, "libTKService.dll")
JLLWrappers.@declare_library_product(libTKShHealing, "libTKShHealing.dll")
JLLWrappers.@declare_library_product(libTKTopAlgo, "libTKTopAlgo.dll")
JLLWrappers.@declare_library_product(libTKV3d, "libTKV3d.dll")
JLLWrappers.@declare_library_product(libTKVCAF, "libTKVCAF.dll")
JLLWrappers.@declare_library_product(libTKVRML, "libTKVRML.dll")
JLLWrappers.@declare_library_product(libTKXCAF, "libTKXCAF.dll")
JLLWrappers.@declare_library_product(libTKXDEIGES, "libTKXDEIGES.dll")
JLLWrappers.@declare_library_product(libTKXDESTEP, "libTKXDESTEP.dll")
JLLWrappers.@declare_library_product(libTKXMesh, "libTKXMesh.dll")
JLLWrappers.@declare_library_product(libTKXSBase, "libTKXSBase.dll")
JLLWrappers.@declare_library_product(libTKXml, "libTKXml.dll")
JLLWrappers.@declare_library_product(libTKXmlL, "libTKXmlL.dll")
JLLWrappers.@declare_library_product(libTKXmlXCAF, "libTKXmlXCAF.dll")
JLLWrappers.@declare_library_product(libTKernel, "libTKernel.dll")
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll)
    JLLWrappers.@init_library_product(
        libTKBO,
        "bin\\libTKBO.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBRep,
        "bin\\libTKBRep.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBin,
        "bin\\libTKBin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinL,
        "bin\\libTKBinL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinXCAF,
        "bin\\libTKBinXCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBool,
        "bin\\libTKBool.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCAF,
        "bin\\libTKCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCDF,
        "bin\\libTKCDF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFeat,
        "bin\\libTKFeat.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFillet,
        "bin\\libTKFillet.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG2d,
        "bin\\libTKG2d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG3d,
        "bin\\libTKG3d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomAlgo,
        "bin\\libTKGeomAlgo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomBase,
        "bin\\libTKGeomBase.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKHLR,
        "bin\\libTKHLR.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKIGES,
        "bin\\libTKIGES.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKLCAF,
        "bin\\libTKLCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMath,
        "bin\\libTKMath.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMesh,
        "bin\\libTKMesh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKOffset,
        "bin\\libTKOffset.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKPrim,
        "bin\\libTKPrim.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKRWMesh,
        "bin\\libTKRWMesh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEP,
        "bin\\libTKSTEP.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEP209,
        "bin\\libTKSTEP209.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEPAttr,
        "bin\\libTKSTEPAttr.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTEPBase,
        "bin\\libTKSTEPBase.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKSTL,
        "bin\\libTKSTL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKService,
        "bin\\libTKService.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKShHealing,
        "bin\\libTKShHealing.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKTopAlgo,
        "bin\\libTKTopAlgo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKV3d,
        "bin\\libTKV3d.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKVCAF,
        "bin\\libTKVCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKVRML,
        "bin\\libTKVRML.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXCAF,
        "bin\\libTKXCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXDEIGES,
        "bin\\libTKXDEIGES.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXDESTEP,
        "bin\\libTKXDESTEP.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXMesh,
        "bin\\libTKXMesh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXSBase,
        "bin\\libTKXSBase.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXml,
        "bin\\libTKXml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlL,
        "bin\\libTKXmlL.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlXCAF,
        "bin\\libTKXmlXCAF.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKernel,
        "bin\\libTKernel.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
