# Autogenerated wrapper script for OCCT_jll for x86_64-apple-darwin
export libTKBO, libTKBRep, libTKBin, libTKBinL, libTKBinXCAF, libTKBool, libTKCAF, libTKCDF, libTKDEGLTF, libTKDEIGES, libTKDEOBJ, libTKDEPLY, libTKDESTEP, libTKDESTL, libTKDEVRML, libTKFeat, libTKFillet, libTKG2d, libTKG3d, libTKGeomAlgo, libTKGeomBase, libTKHLR, libTKLCAF, libTKMath, libTKMesh, libTKOffset, libTKPrim, libTKRWMesh, libTKService, libTKShHealing, libTKTopAlgo, libTKV3d, libTKVCAF, libTKXCAF, libTKXMesh, libTKXSBase, libTKXml, libTKXmlL, libTKXmlXCAF, libTKernel

using FreeType2_jll
JLLWrappers.@generate_wrapper_header("OCCT")
JLLWrappers.@declare_library_product(libTKBO, "@rpath/libTKBO.7.9.dylib")
JLLWrappers.@declare_library_product(libTKBRep, "@rpath/libTKBRep.7.9.dylib")
JLLWrappers.@declare_library_product(libTKBin, "@rpath/libTKBin.7.9.dylib")
JLLWrappers.@declare_library_product(libTKBinL, "@rpath/libTKBinL.7.9.dylib")
JLLWrappers.@declare_library_product(libTKBinXCAF, "@rpath/libTKBinXCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKBool, "@rpath/libTKBool.7.9.dylib")
JLLWrappers.@declare_library_product(libTKCAF, "@rpath/libTKCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKCDF, "@rpath/libTKCDF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDEGLTF, "@rpath/libTKDEGLTF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDEIGES, "@rpath/libTKDEIGES.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDEOBJ, "@rpath/libTKDEOBJ.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDEPLY, "@rpath/libTKDEPLY.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDESTEP, "@rpath/libTKDESTEP.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDESTL, "@rpath/libTKDESTL.7.9.dylib")
JLLWrappers.@declare_library_product(libTKDEVRML, "@rpath/libTKDEVRML.7.9.dylib")
JLLWrappers.@declare_library_product(libTKFeat, "@rpath/libTKFeat.7.9.dylib")
JLLWrappers.@declare_library_product(libTKFillet, "@rpath/libTKFillet.7.9.dylib")
JLLWrappers.@declare_library_product(libTKG2d, "@rpath/libTKG2d.7.9.dylib")
JLLWrappers.@declare_library_product(libTKG3d, "@rpath/libTKG3d.7.9.dylib")
JLLWrappers.@declare_library_product(libTKGeomAlgo, "@rpath/libTKGeomAlgo.7.9.dylib")
JLLWrappers.@declare_library_product(libTKGeomBase, "@rpath/libTKGeomBase.7.9.dylib")
JLLWrappers.@declare_library_product(libTKHLR, "@rpath/libTKHLR.7.9.dylib")
JLLWrappers.@declare_library_product(libTKLCAF, "@rpath/libTKLCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKMath, "@rpath/libTKMath.7.9.dylib")
JLLWrappers.@declare_library_product(libTKMesh, "@rpath/libTKMesh.7.9.dylib")
JLLWrappers.@declare_library_product(libTKOffset, "@rpath/libTKOffset.7.9.dylib")
JLLWrappers.@declare_library_product(libTKPrim, "@rpath/libTKPrim.7.9.dylib")
JLLWrappers.@declare_library_product(libTKRWMesh, "@rpath/libTKRWMesh.7.9.dylib")
JLLWrappers.@declare_library_product(libTKService, "@rpath/libTKService.7.9.dylib")
JLLWrappers.@declare_library_product(libTKShHealing, "@rpath/libTKShHealing.7.9.dylib")
JLLWrappers.@declare_library_product(libTKTopAlgo, "@rpath/libTKTopAlgo.7.9.dylib")
JLLWrappers.@declare_library_product(libTKV3d, "@rpath/libTKV3d.7.9.dylib")
JLLWrappers.@declare_library_product(libTKVCAF, "@rpath/libTKVCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXCAF, "@rpath/libTKXCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXMesh, "@rpath/libTKXMesh.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXSBase, "@rpath/libTKXSBase.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXml, "@rpath/libTKXml.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXmlL, "@rpath/libTKXmlL.7.9.dylib")
JLLWrappers.@declare_library_product(libTKXmlXCAF, "@rpath/libTKXmlXCAF.7.9.dylib")
JLLWrappers.@declare_library_product(libTKernel, "@rpath/libTKernel.7.9.dylib")
function __init__()
    JLLWrappers.@generate_init_header(FreeType2_jll)
    JLLWrappers.@init_library_product(
        libTKBO,
        "lib/libTKBO.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBRep,
        "lib/libTKBRep.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBin,
        "lib/libTKBin.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinL,
        "lib/libTKBinL.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBinXCAF,
        "lib/libTKBinXCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKBool,
        "lib/libTKBool.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCAF,
        "lib/libTKCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKCDF,
        "lib/libTKCDF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDEGLTF,
        "lib/libTKDEGLTF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDEIGES,
        "lib/libTKDEIGES.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDEOBJ,
        "lib/libTKDEOBJ.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDEPLY,
        "lib/libTKDEPLY.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDESTEP,
        "lib/libTKDESTEP.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDESTL,
        "lib/libTKDESTL.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKDEVRML,
        "lib/libTKDEVRML.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFeat,
        "lib/libTKFeat.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKFillet,
        "lib/libTKFillet.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG2d,
        "lib/libTKG2d.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKG3d,
        "lib/libTKG3d.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomAlgo,
        "lib/libTKGeomAlgo.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKGeomBase,
        "lib/libTKGeomBase.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKHLR,
        "lib/libTKHLR.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKLCAF,
        "lib/libTKLCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMath,
        "lib/libTKMath.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKMesh,
        "lib/libTKMesh.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKOffset,
        "lib/libTKOffset.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKPrim,
        "lib/libTKPrim.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKRWMesh,
        "lib/libTKRWMesh.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKService,
        "lib/libTKService.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKShHealing,
        "lib/libTKShHealing.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKTopAlgo,
        "lib/libTKTopAlgo.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKV3d,
        "lib/libTKV3d.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKVCAF,
        "lib/libTKVCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXCAF,
        "lib/libTKXCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXMesh,
        "lib/libTKXMesh.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXSBase,
        "lib/libTKXSBase.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXml,
        "lib/libTKXml.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlL,
        "lib/libTKXmlL.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKXmlXCAF,
        "lib/libTKXmlXCAF.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libTKernel,
        "lib/libTKernel.7.9.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
